/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paneles;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author abiga
 */
public class Inter extends javax.swing.JFrame {
    /**
     * Creates new form Inter
     */
    public Inter( String nombreAdmin) {
        initComponents();
        labelUser.setText(nombreAdmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnMenu = new rsbuttom.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();
        labelUser = new rsbuttom.RSButtonMetro();
        btnCerrar = new rsbuttom.RSButtonMetro();
        menuLateral = new javax.swing.JPanel();
        btnAcceso = new rsbuttom.RSButtonMetro();
        btnControlClientes = new rsbuttom.RSButtonMetro();
        btnControlEntrenadores = new rsbuttom.RSButtonMetro();
        btnControlAdministradores = new rsbuttom.RSButtonMetro();
        btnControlAdministradores1 = new rsbuttom.RSButtonMetro();
        panelInterfaz = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(26, 26, 26));

        btnMenu.setBackground(new java.awt.Color(26, 26, 26));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        btnMenu.setColorNormal(new java.awt.Color(26, 26, 26));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(26, 26, 26));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/encabezado_logo.png"))); // NOI18N

        labelUser.setBackground(new java.awt.Color(26, 26, 26));
        labelUser.setForeground(new java.awt.Color(255, 153, 0));
        labelUser.setText("User");
        labelUser.setColorNormal(new java.awt.Color(26, 26, 26));
        labelUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelUserActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(26, 26, 26));
        btnCerrar.setText("Cerrar sesión");
        btnCerrar.setColorNormal(new java.awt.Color(26, 26, 26));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuLateral.setBackground(new java.awt.Color(26, 26, 26));

        btnAcceso.setBackground(new java.awt.Color(26, 26, 26));
        btnAcceso.setText("Acceso");
        btnAcceso.setColorNormal(new java.awt.Color(26, 26, 26));
        btnAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccesoActionPerformed(evt);
            }
        });

        btnControlClientes.setBackground(new java.awt.Color(26, 26, 26));
        btnControlClientes.setText("Clientes");
        btnControlClientes.setColorNormal(new java.awt.Color(26, 26, 26));
        btnControlClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlClientesActionPerformed(evt);
            }
        });

        btnControlEntrenadores.setBackground(new java.awt.Color(26, 26, 26));
        btnControlEntrenadores.setText("Entrenadores");
        btnControlEntrenadores.setColorNormal(new java.awt.Color(26, 26, 26));
        btnControlEntrenadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlEntrenadoresActionPerformed(evt);
            }
        });

        btnControlAdministradores.setBackground(new java.awt.Color(26, 26, 26));
        btnControlAdministradores.setText("Administradores");
        btnControlAdministradores.setColorNormal(new java.awt.Color(26, 26, 26));
        btnControlAdministradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlAdministradoresActionPerformed(evt);
            }
        });

        btnControlAdministradores1.setBackground(new java.awt.Color(26, 26, 26));
        btnControlAdministradores1.setText("Asistencias");
        btnControlAdministradores1.setColorNormal(new java.awt.Color(26, 26, 26));
        btnControlAdministradores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlAdministradores1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLateralLayout = new javax.swing.GroupLayout(menuLateral);
        menuLateral.setLayout(menuLateralLayout);
        menuLateralLayout.setHorizontalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAcceso, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnControlAdministradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnControlClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnControlEntrenadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnControlAdministradores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuLateralLayout.setVerticalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnControlClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnControlEntrenadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnControlAdministradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnControlAdministradores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        panelInterfaz.setBackground(new java.awt.Color(38, 38, 38));

        javax.swing.GroupLayout panelInterfazLayout = new javax.swing.GroupLayout(panelInterfaz);
        panelInterfaz.setLayout(panelInterfazLayout);
        panelInterfazLayout.setHorizontalGroup(
            panelInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelInterfazLayout.setVerticalGroup(
            panelInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(menuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelInterfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInterfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnControlAdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlAdministradoresActionPerformed
        // TODO add your handling code here:
        mostrarPanel(new PanelAdministradores());
    }//GEN-LAST:event_btnControlAdministradoresActionPerformed

    private void btnControlEntrenadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlEntrenadoresActionPerformed
        // TODO add your handling code here:
        mostrarPanel(new PanelEntrenadores());
    }//GEN-LAST:event_btnControlEntrenadoresActionPerformed

    private void btnControlClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlClientesActionPerformed
        // TODO add your handling code here:
        mostrarPanel(new PanelClientes());
    }//GEN-LAST:event_btnControlClientesActionPerformed

    private void btnAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesoActionPerformed
        // TODO add your handling code here:
        mostrarPanel(new PanelAcceso());
    }//GEN-LAST:event_btnAccesoActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        if(menuLateral.isVisible()){
            menuLateral.setVisible(false);
        }else{
            menuLateral.setVisible(true);
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void labelUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelUserActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        int confirmar = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres cerrar sesión?", "Confirmar", JOptionPane.YES_NO_OPTION);
    if (confirmar == JOptionPane.YES_OPTION) {
        this.dispose(); // Cierra la ventana actual (Inter)
        LoginFrame login = new LoginFrame(); // Crear instancia del JFrame de login
        login.setVisible(true); // Mostrar ventana de login
    }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnControlAdministradores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlAdministradores1ActionPerformed
        // TODO add your handling code here:
        mostrarPanel(new PanelAsistencias());
    }//GEN-LAST:event_btnControlAdministradores1ActionPerformed

    private void mostrarPanel(JPanel panel){
 panel.setSize(panelInterfaz.getSize());
    panel.setLocation(0, 0);

    panelInterfaz.removeAll();
    panelInterfaz.add(panel);
    panelInterfaz.revalidate();
    panelInterfaz.repaint();
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnAcceso;
    private rsbuttom.RSButtonMetro btnCerrar;
    private rsbuttom.RSButtonMetro btnControlAdministradores;
    private rsbuttom.RSButtonMetro btnControlAdministradores1;
    private rsbuttom.RSButtonMetro btnControlClientes;
    private rsbuttom.RSButtonMetro btnControlEntrenadores;
    private rsbuttom.RSButtonMetro btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rsbuttom.RSButtonMetro labelUser;
    private javax.swing.JPanel menuLateral;
    private javax.swing.JPanel panelInterfaz;
    // End of variables declaration//GEN-END:variables
}
