/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import control.AdmDatos;
import control.AdministradorJpaController;
import control.exceptions.IllegalOrphanException;
import control.exceptions.NonexistentEntityException;
import control_datos.MtAdministrador;
import huella.huella;
import java.awt.HeadlessException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Administrador;

/**
 *
 * @author abiga
 */
public class PanelAdministradores extends javax.swing.JPanel {
private huella lector_huella ;
private huella lector_huella_new ;//Para actualizar la huella

private Administrador administrador;
private final AdministradorJpaController cAdministradores;
private final AdmDatos adm;
private final List<Administrador> administradores;
private final MtAdministrador mta;
    /**
     * Creates new form PanelAdministradores
     */
    public PanelAdministradores() {
        initComponents();
        lector_huella = new huella(imagen_huella, area_huella);
    lector_huella_new = new huella(imagen_huella2, area_huella2);

    adm = new AdmDatos();
    cAdministradores = new AdministradorJpaController(adm.getEmf());
    administradores = cAdministradores.findAdministradorEntities();
    mta = new MtAdministrador(administradores);
    tableAdministradores.setModel(mta);

    // Desactivar pestañas (excepto la 0)
    jTabbedPane1.setEnabledAt(1, false);
    jTabbedPane1.setEnabledAt(2, false); 

    // Bloquear los datos del cliente cuando entre a la vista donde los edita
    txtEditNombreAdministrador.setEditable(false); // nombre
    txtEditCorreo.setEditable(false); // correo
    txtEditTelefono.setEditable(false); // teléfono
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAdministradores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FechaA = new javax.swing.JLabel();
        txtNombreAdministrador = new javax.swing.JTextField();
        txtCorreoAdministrador = new javax.swing.JTextField();
        txtTelefonoAdministrador = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        btnAgregarAdministrador = new javax.swing.JButton();
        HoraA = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        imagen_huella = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area_huella = new javax.swing.JTextArea();
        jButton14 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEditNombreAdministrador = new javax.swing.JTextField();
        txtEditCorreo = new javax.swing.JTextField();
        txtEditTelefono = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        imagen_huella2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        area_huella2 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        psw = new javax.swing.JPasswordField();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();

        jButton15.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton15.setText("Editar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton17.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton17.setText("Nueva Huella");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(26, 26, 26));

        jTabbedPane1.setBackground(new java.awt.Color(38, 38, 38));
        jTabbedPane1.setForeground(new java.awt.Color(38, 38, 38));

        jPanel1.setBackground(new java.awt.Color(38, 38, 38));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administracion De Administradores");

        btnEditar.setBackground(new java.awt.Color(51, 51, 51));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tableAdministradores.setBackground(new java.awt.Color(34, 34, 34));
        tableAdministradores.setForeground(new java.awt.Color(255, 255, 255));
        tableAdministradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableAdministradores);
        if (tableAdministradores.getColumnModel().getColumnCount() > 0) {
            tableAdministradores.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            tableAdministradores.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            tableAdministradores.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            tableAdministradores.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("VISTA DE ADMIN", jPanel1);

        jPanel2.setBackground(new java.awt.Color(38, 38, 38));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Agregar Nuevo Administrador");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefono");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correo");

        FechaA.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        FechaA.setForeground(new java.awt.Color(255, 255, 255));
        FechaA.setText("12/12/2012");

        txtNombreAdministrador.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtNombreAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAdministradorActionPerformed(evt);
            }
        });

        txtCorreoAdministrador.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        txtTelefonoAdministrador.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnAgregarAdministrador.setBackground(new java.awt.Color(51, 51, 51));
        btnAgregarAdministrador.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnAgregarAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarAdministrador.setText("Agregar");
        btnAgregarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAdministradorActionPerformed(evt);
            }
        });

        HoraA.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        HoraA.setForeground(new java.awt.Color(255, 255, 255));
        HoraA.setText("9:12:00");

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Capturar Huella");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        imagen_huella.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        imagen_huella.setForeground(new java.awt.Color(255, 255, 255));
        imagen_huella.setText("Aquí para huella");

        area_huella.setColumns(20);
        area_huella.setRows(5);
        jScrollPane2.setViewportView(area_huella);

        jButton14.setBackground(new java.awt.Color(51, 51, 51));
        jButton14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Limpiar Huella");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HoraA, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(FechaA)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTelefonoAdministrador)
                                    .addComponent(txtCorreoAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                        .addGap(156, 156, 156))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(btnAgregarAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(imagen_huella, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jButton7)))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FechaA)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(HoraA, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCorreoAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefonoAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarAdministrador)
                            .addComponent(jButton6))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(imagen_huella, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("AGREGAR ADMIN", jPanel2);

        jPanel3.setBackground(new java.awt.Color(38, 38, 38));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Editar Los Datos De Un Aministrador ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correo");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Telefono");

        txtEditNombreAdministrador.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtEditNombreAdministrador.setText("jTextField4");
        txtEditNombreAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditNombreAdministradorActionPerformed(evt);
            }
        });

        txtEditCorreo.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtEditCorreo.setText("jTextField5");

        txtEditTelefono.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtEditTelefono.setText("jTextField6");

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Editar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(51, 51, 51));
        jButton9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Editar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(51, 51, 51));
        jButton10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Editar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(51, 51, 51));
        jButton11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Guardar Cambios");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(51, 51, 51));
        jButton12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Cancelar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(51, 51, 51));
        jButton13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Nueva Huella");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        imagen_huella2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        imagen_huella2.setForeground(new java.awt.Color(255, 255, 255));
        imagen_huella2.setText("Aquí para huella");

        area_huella2.setColumns(20);
        area_huella2.setRows(5);
        jScrollPane3.setViewportView(area_huella2);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Password");

        jButton16.setBackground(new java.awt.Color(51, 51, 51));
        jButton16.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Editar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(51, 51, 51));
        jButton18.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("Limpiar Huella");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(imagen_huella2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEditNombreAdministrador)
                                    .addComponent(txtEditCorreo)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtEditTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton10))
                                    .addComponent(psw))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8)
                                    .addComponent(jButton9)
                                    .addComponent(jButton16)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(103, 103, 103))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jButton13)
                .addGap(74, 74, 74)
                .addComponent(jButton18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton16))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(psw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEditNombreAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEditCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEditTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagen_huella2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("EDITAR DATOS ADMINS", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Obtener el índice de la fila seleccionada en la tabla
        int filaSeleccionada = tableAdministradores.getSelectedRow();

        // Verificar si hay alguna fila seleccionada
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor, seleccione un cliente para editar.",
                "Ninguna selección",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Administrador admin = administradores.get(filaSeleccionada);

        // Obtener valores de la fila seleccionada y colocarlos en los txtFields
        txtEditNombreAdministrador.setText(tableAdministradores.getValueAt(filaSeleccionada, 1).toString());
        txtEditCorreo.setText(tableAdministradores.getValueAt(filaSeleccionada, 2).toString());
        txtEditTelefono.setText(tableAdministradores.getValueAt(filaSeleccionada, 3).toString());
        psw.setText(admin.getPassword());


        jTabbedPane1.setEnabledAt(2, true);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tableAdministradores.getSelectedRow();

        // Verificar si hay alguna fila seleccionada
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor, seleccione un administrador para eliminar.",
                "Ninguna selección",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Confirmar eliminación con el usuario
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Está seguro de que desea eliminar éste administrador?",
            "Confirmar eliminación",
            javax.swing.JOptionPane.YES_NO_OPTION);

        // Si el usuario confirma la eliminación
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            try {
                // Obtener el cliente seleccionado
                Administrador administradorSeleccionado = administradores.get(filaSeleccionada);

                // Obtener el ID del cliente (idcliente es un Integer según la clase TutorJpaController)
                Integer idAdministrador = administradorSeleccionado.getAdministradorId();

                // Eliminar de la base de datos usando el ID
                cAdministradores.destroy(idAdministrador);

                // Eliminar de la lista local
                administradores.remove(filaSeleccionada);

                // Actualizar la tabla
                mta.fireTableDataChanged();

                // Mostrar mensaje de éxito
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Administrador eliminado correctamente.",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            } catch (NonexistentEntityException e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Error: El Administrador ya no existe en la base de datos.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                // Actualizar la tabla de todas formas
                administradores.remove(filaSeleccionada);
                mta.fireTableDataChanged();
            } catch (HeadlessException e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al eliminar el administrador: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            } catch (IllegalOrphanException ex) {
                Logger.getLogger(PanelAdministradores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtNombreAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAdministradorActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Estás segur@ de regresar?\nSe perderán los datos no guardados.",
            "Confirmación",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            jTabbedPane1.setSelectedIndex(0);   // Ir al panel principal
            jTabbedPane1.setEnabledAt(1, false); // Desactivar pestaña de agregar
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnAgregarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAdministradorActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombreAdministrador.getText().trim();
        String correo = txtCorreoAdministrador.getText().trim();
        String telefono = txtTelefonoAdministrador.getText().trim();

        boolean validar = validarCampos(nombre, correo, telefono);
        if (!validar) {
            return;
        }

        try {
            byte[] datosHuella = lector_huella.obtenerDatosHuella();
            if (datosHuella == null || datosHuella.length == 0) {
                JOptionPane.showMessageDialog(this, "No se pudo obtener la huella digital.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Verificar si el entrenador ya existe por nombre
            for (Administrador e : administradores) {
                if (e.getNombreCompleto().equalsIgnoreCase(nombre)) {
                    JOptionPane.showMessageDialog(this, "El entrenador con el nombre \"" + nombre + "\" ya existe.", "Dato duplicado", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (e.getCorreoElectronico().equals(correo)) {
                    JOptionPane.showMessageDialog(this, "El entrenador con el correo \"" + nombre + "\" ya existe.", "Dato duplicado", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (e.getTelefonoContacto().equals(telefono)) {
                    JOptionPane.showMessageDialog(this, "El entrenador con el Numero de telefono \"" + nombre + "\" ya existe.", "Dato duplicado", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            // Crear nuevo entrenador
            Administrador administrador = new Administrador();
            administrador.setNombreCompleto(nombre);
            administrador.setCorreoElectronico(correo);
            administrador.setTelefonoContacto(telefono);
            administrador.setHuellaDactilar(datosHuella); // Asegúrate que el atributo sea 'huella' o 'huellaDactilar' según tu entidad

            // Guardar en la base de datos
            cAdministradores.create(administrador); // Asegúrate de tener bien tu controlador JPA
            administradores.add(administrador);
            mta.fireTableDataChanged();

            JOptionPane.showMessageDialog(this, "Entrenador registrado correctamente.");

            // Limpiar campos después del registro exitoso
            txtNombreAdministrador.setText("");
            txtCorreoAdministrador.setText("");
            txtTelefonoAdministrador.setText("");
            lector_huella.limpiarDatos();

        } catch (IllegalStateException ex) {
            JOptionPane.showMessageDialog(this, "Error al obtener huella: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAgregarAdministradorActionPerformed

    public boolean validarCampos(String campo2, String email, String telefono) {
    // Validación de campo2
    if (campo2.isEmpty()) {
        JOptionPane.showMessageDialog(null, "El campo de nombre no debe estar vacío.");
        return false;
    } else if (!campo2.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
        JOptionPane.showMessageDialog(null, "El nombre solo debe contener letras y espacios.");
        return false;
    }

    // Validación de email
    String emailRegex = "^[a-zA-Z0-9.]+@[a-zA-Z0-9-]+\\.[a-zA-Z]{2,6}$";
    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(null, "El correo electrónico no debe estar vacío.");
        return false;
    } else if (!email.matches(emailRegex)) {
        JOptionPane.showMessageDialog(null, "El correo electrónico no cumple con el formato estándar (ej: usuario@dominio.com).");
        return false;
    }

    // Validación de teléfono
    if (telefono.isEmpty()) {
        JOptionPane.showMessageDialog(null, "El número de teléfono no debe estar vacío.");
        return false;
    } else if (!telefono.matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "El teléfono solo debe contener números.");
        return false;
    } else if (telefono.length() != 10) {
        JOptionPane.showMessageDialog(null, "El número de teléfono debe contener exactamente 10 dígitos.");
        return false;
    }

    return true;
} 
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        lector_huella.iniciar();
        lector_huella.start();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        txtEditNombreAdministrador.setEditable(true); // Activa el campo de nombre
        txtEditNombreAdministrador.requestFocus();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        txtEditCorreo.setEditable(true); // Activa el campo de nombre
        txtEditCorreo.requestFocus();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        txtEditTelefono.setEditable(true); // Activa el campo de nombre
        txtEditTelefono.requestFocus();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        String nombre = txtEditNombreAdministrador.getText().trim();
        String correo = txtEditCorreo.getText().trim();
        String telefono = txtEditTelefono.getText().trim();
        char[] password= psw.getPassword();
        String passString = new String(password);

        boolean validar = validarCampos(nombre, correo, telefono);
        if (!validar) {
            return;
        }

        int filaSeleccionada = tableAdministradores.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente para editar.", "Sin selección", JOptionPane.WARNING_MESSAGE);
            return;
        }
        byte[] datosHuella = null;

        try {
            // Intentar obtener una nueva huella
            datosHuella = lector_huella_new.obtenerDatosHuella();
        } catch (IllegalStateException ex) {
            // Si no se capturó ninguna huella, solo mostrar aviso informativo (no es un error)
            System.out.println("No se actualizó la huella: " + ex.getMessage());
            // También puedes mostrar un mensaje opcional al usuario:
            // JOptionPane.showMessageDialog(null, "No se actualizó la huella: " + ex.getMessage(), "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }

        try {

            // Crear nuevo entrenador
            Administrador AdministradorExiste = administradores.get(filaSeleccionada);

            AdministradorExiste.setNombreCompleto(nombre);
            AdministradorExiste.setCorreoElectronico(correo);
            AdministradorExiste.setTelefonoContacto(telefono);
            AdministradorExiste.setPassword(passString);
            // Actualizar huella solo si hay una nueva válida
            if (datosHuella != null && datosHuella.length > 0) {
                AdministradorExiste.setHuellaDactilar(datosHuella);
            }

            // Actualizar en base de datos
            cAdministradores.edit(AdministradorExiste);
            mta.fireTableRowsUpdated(filaSeleccionada, filaSeleccionada);
            lector_huella_new.limpiarDatos();

            JOptionPane.showMessageDialog(this, "Entrenador registrado correctamente.");

        } catch (IllegalStateException ex) {
            JOptionPane.showMessageDialog(this, "Error al obtener huella: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Estás segur@ de regresar?\nSe perderán los cambios no guardados.",
            "Confirmación",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            jTabbedPane1.setSelectedIndex(0);   // Volver al panel principal
            jTabbedPane1.setEnabledAt(2, false); // Desactivar pestaña de edición
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        lector_huella.limpiarDatos();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        psw.setEditable(true); // Activa el campo de nombre
        psw.requestFocus();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        lector_huella_new.iniciar();
        lector_huella_new.start();
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        lector_huella_new.limpiarDatos();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void txtEditNombreAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditNombreAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditNombreAdministradorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FechaA;
    private javax.swing.JLabel HoraA;
    private javax.swing.JTextArea area_huella;
    private javax.swing.JTextArea area_huella2;
    private javax.swing.JButton btnAgregarAdministrador;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel imagen_huella;
    private javax.swing.JLabel imagen_huella2;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField psw;
    private javax.swing.JTable tableAdministradores;
    private javax.swing.JTextField txtCorreoAdministrador;
    private javax.swing.JTextField txtEditCorreo;
    private javax.swing.JTextField txtEditNombreAdministrador;
    private javax.swing.JTextField txtEditTelefono;
    private javax.swing.JTextField txtNombreAdministrador;
    private javax.swing.JTextField txtTelefonoAdministrador;
    // End of variables declaration//GEN-END:variables
}
