/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import control.AdmDatos;
import control.EntrenadorJpaController;
import control.EspecialidadesJpaController;
import control.exceptions.IllegalOrphanException;
import control.exceptions.NonexistentEntityException;
import control_datos.MtEntrenador;
import control_datos.MtEspecialidades;
import huella.huella;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import modelo.Entrenador;
import modelo.Especialidades;

/**
 *
 * @author abiga
 */
public class PanelEntrenadores extends javax.swing.JPanel {
private huella lector_huella ;
private huella lector_huella_new ;//Para actualizar la huella

private Entrenador entrenador;
private final EntrenadorJpaController cEntrenadores;

private Especialidades especialidad;
private final EspecialidadesJpaController cEspecialidades;

private final AdmDatos adm;

private final List<Entrenador> entrenadores;
private final List<Especialidades> especialidades;

private final MtEntrenador mte;
private final MtEspecialidades mtespe;

    /**
     * Creates new form PanelEntrenadores
     */
    public PanelEntrenadores() {
        initComponents();
        
    adm = new AdmDatos();
    cEntrenadores = new EntrenadorJpaController(adm.getEmf());
    entrenadores = cEntrenadores.findEntrenadorEntities();
    mte = new MtEntrenador(entrenadores);
    tableEntrenadores.setModel(mte);
    
    cEspecialidades = new EspecialidadesJpaController(adm.getEmf());
    especialidades = cEspecialidades.findEspecialidadesEntities();
    mtespe = new MtEspecialidades(especialidades);
    
    lector_huella = new huella(imagen_huella, area_huella);
    lector_huella_new = new huella(imagen_huella2, area_huella2);
    
   //Para rellenar el comboBox con las especialidades
    comboEspecialidades.removeAllItems();
    for (Especialidades esp : especialidades) {
        comboEspecialidades.addItem(esp.getNombreEspecialidad());
    }
    
    //Para rellenar el comboBox con las especialidades
    comboEditEspecialidad.removeAllItems();
    for (Especialidades esp2 : especialidades) {
        comboEditEspecialidad.addItem(esp2.getNombreEspecialidad());
    }

    // Desactivar pestañas (excepto la 0)
    jTabbedPane1.setEnabledAt(1, false);
    jTabbedPane1.setEnabledAt(2, false); 

    // Bloquear los datos del cliente cuando entre a la vista donde los edita
    txtEditEntrenador.setEditable(false); // nombre
    txtEditCorreo.setEditable(false); // correo
    txtEditTelefono.setEditable(false); // teléfono
    comboEditEspecialidad.setEditable(false);

    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    String fechaActual = formato.format(new Date());
    FechaA.setText(fechaActual); // Fecha en el registro de administradores

    // Inicia la hora actual con formato
    SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
    // Crear un Timer que se ejecuta cada 1000 ms (1 segundo)
    Timer timer = new Timer(1000, e -> {
        String horaActual = formatoHora.format(new Date());
        HoraA.setText(horaActual);
    });
    timer.start();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarEntrenador = new javax.swing.JButton();
        btnEliminarEntrenador = new javax.swing.JButton();
        btnEditarEntrenador = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEntrenadores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        HoraA = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FechaA = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreEntrenador = new javax.swing.JTextField();
        txtTelefonoEntrenador = new javax.swing.JTextField();
        txtCorreoEntrenador = new javax.swing.JTextField();
        comboEspecialidades = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        imagen_huella = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area_huella = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEditEntrenador = new javax.swing.JTextField();
        txtEditCorreo = new javax.swing.JTextField();
        txtEditTelefono = new javax.swing.JTextField();
        comboEditEspecialidad = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btnEditEntrenador = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        imagen_huella2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        area_huella2 = new javax.swing.JTextArea();
        limpia = new javax.swing.JButton();

        setBackground(new java.awt.Color(26, 26, 26));

        jTabbedPane1.setBackground(new java.awt.Color(38, 38, 38));

        jPanel1.setBackground(new java.awt.Color(38, 38, 38));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admnistración De Entrenadores ");

        btnAgregarEntrenador.setBackground(new java.awt.Color(51, 51, 51));
        btnAgregarEntrenador.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnAgregarEntrenador.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarEntrenador.setText("Agregar");
        btnAgregarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEntrenadorActionPerformed(evt);
            }
        });

        btnEliminarEntrenador.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminarEntrenador.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEliminarEntrenador.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEntrenador.setText("Eliminar");
        btnEliminarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEntrenadorActionPerformed(evt);
            }
        });

        btnEditarEntrenador.setBackground(new java.awt.Color(51, 51, 51));
        btnEditarEntrenador.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEditarEntrenador.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarEntrenador.setText("Editar");
        btnEditarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEntrenadorActionPerformed(evt);
            }
        });

        tableEntrenadores.setBackground(new java.awt.Color(34, 34, 34));
        tableEntrenadores.setForeground(new java.awt.Color(255, 255, 255));
        tableEntrenadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableEntrenadores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnAgregarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnEliminarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnEditarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarEntrenador)
                    .addComponent(btnEditarEntrenador)
                    .addComponent(btnAgregarEntrenador))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CONTROL DE ENTRENADORES ", jPanel1);

        jPanel2.setBackground(new java.awt.Color(38, 38, 38));

        HoraA.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        HoraA.setForeground(new java.awt.Color(255, 255, 255));
        HoraA.setText("9:00:00");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agregar Nuevo Entrenador ");

        FechaA.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        FechaA.setForeground(new java.awt.Color(255, 255, 255));
        FechaA.setText("12/12/1212");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefono");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Especialidad");

        txtNombreEntrenador.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        txtTelefonoEntrenador.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        txtCorreoEntrenador.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        comboEspecialidades.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        comboEspecialidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEspecialidadesActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Agregar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Capturar Huella");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        imagen_huella.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        imagen_huella.setForeground(new java.awt.Color(255, 255, 255));
        imagen_huella.setText("Aqui para la huella");

        area_huella.setColumns(20);
        area_huella.setRows(5);
        jScrollPane2.setViewportView(area_huella);

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Limpiar Huella");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Regresar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HoraA, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FechaA, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreoEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefonoEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(161, 161, 161)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jButton1)
                .addGap(44, 44, 44)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(imagen_huella, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoraA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaA))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCorreoEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefonoEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagen_huella, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("AGREGAR ENTRENADOR", jPanel2);

        jPanel3.setBackground(new java.awt.Color(38, 38, 38));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Editar Datos De Un Entrenador");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Correo");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Telefono");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Especialidad");

        txtEditEntrenador.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtEditEntrenador.setText("jTextField4");

        txtEditCorreo.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtEditCorreo.setText("jTextField5");

        txtEditTelefono.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtEditTelefono.setText("jTextField6");

        comboEditEspecialidad.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        comboEditEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEditEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEditEspecialidadActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Editar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Editar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(51, 51, 51));
        jButton9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Editar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(51, 51, 51));
        jButton10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Editar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        btnEditEntrenador.setBackground(new java.awt.Color(51, 51, 51));
        btnEditEntrenador.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEditEntrenador.setForeground(new java.awt.Color(255, 255, 255));
        btnEditEntrenador.setText("Guardar Cambios");
        btnEditEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditEntrenadorActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(51, 51, 51));
        jButton12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Regresar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Nueva Huella");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        imagen_huella2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        imagen_huella2.setForeground(new java.awt.Color(255, 255, 255));
        imagen_huella2.setText("NUEVA HUELLA");

        area_huella2.setColumns(20);
        area_huella2.setRows(5);
        jScrollPane3.setViewportView(area_huella2);

        limpia.setBackground(new java.awt.Color(51, 51, 51));
        limpia.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        limpia.setForeground(new java.awt.Color(255, 255, 255));
        limpia.setText("LImpiar Huella");
        limpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtEditCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEditEntrenador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(txtEditTelefono))
                                        .addGap(40, 40, 40))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboEditEspecialidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(limpia)))
                        .addGap(131, 131, 131))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(imagen_huella2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(301, 301, 301))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btnEditEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEditEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEditCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEditTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(comboEditEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(limpia))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagen_huella2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditEntrenador)
                    .addComponent(jButton12))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("EDITAR DATOS DE ENTRENADOR", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEntrenadorActionPerformed
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnAgregarEntrenadorActionPerformed

    private void btnEliminarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEntrenadorActionPerformed
        // TODO add your handling code here:
        // Obtener el índice de la fila seleccionada en la tabla
        int filaSeleccionada = tableEntrenadores.getSelectedRow();

        // Verificar si hay alguna fila seleccionada
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor, seleccione un entrenador para eliminar.",
                "Ninguna selección",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Confirmar eliminación con el usuario
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Está seguro de que desea eliminar éste entrenador?",
            "Confirmar eliminación",
            javax.swing.JOptionPane.YES_NO_OPTION);

        // Si el usuario confirma la eliminación
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            try {
                // Obtener el cliente seleccionado
                Entrenador entrenadorSeleccionado = entrenadores.get(filaSeleccionada);

                // Obtener el ID del cliente (idcliente es un Integer según la clase TutorJpaController)
                Integer idEntrenador = entrenadorSeleccionado.getEntrenadorId();

                // Eliminar de la base de datos usando el ID
                cEntrenadores.destroy(idEntrenador);

                // Eliminar de la lista local
                entrenadores.remove(filaSeleccionada);

                // Actualizar la tabla
                mte.fireTableDataChanged();

                // Mostrar mensaje de éxito
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Entrenador eliminado correctamente.",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            } catch (NonexistentEntityException e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Error: El entrenador ya no existe en la base de datos.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                // Actualizar la tabla de todas formas
                entrenadores.remove(filaSeleccionada);
                mte.fireTableDataChanged();
            } catch (HeadlessException e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al eliminar el entrenador: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            } catch (IllegalOrphanException ex) {
                Logger.getLogger(PanelClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEliminarEntrenadorActionPerformed

    private void btnEditarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEntrenadorActionPerformed

        // Obtener el índice de la fila seleccionada en la tabla
        int filaSeleccionada = tableEntrenadores.getSelectedRow();

        // Verificar si hay alguna fila seleccionada
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor, seleccione un cliente para editar.",
                "Ninguna selección",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener valores de la fila seleccionada y colocarlos en los txtFields
        txtEditEntrenador.setText(tableEntrenadores.getValueAt(filaSeleccionada, 1).toString());
        txtEditCorreo.setText(tableEntrenadores.getValueAt(filaSeleccionada, 2).toString());
        txtEditTelefono.setText(tableEntrenadores.getValueAt(filaSeleccionada, 3).toString());
        comboEditEspecialidad.setSelectedItem(tableEntrenadores.getValueAt(filaSeleccionada, 4).toString());

        jTabbedPane1.setEnabledAt(2, true);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnEditarEntrenadorActionPerformed

    private void comboEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEspecialidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEspecialidadesActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombreEntrenador.getText().trim();
        String correo = txtCorreoEntrenador.getText().trim();
        String telefono = txtTelefonoEntrenador.getText().trim();

        boolean validar = validarCampos(nombre, correo, telefono);
        if (!validar) {
            return;
        }

        try {
            byte[] datosHuella = lector_huella.obtenerDatosHuella();
            if (datosHuella == null || datosHuella.length == 0) {
                JOptionPane.showMessageDialog(this, "No se pudo obtener la huella digital.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Verificar si el entrenador ya existe por nombre
            for (Entrenador e : entrenadores) {
                if (e.getNombreCompleto().equalsIgnoreCase(nombre)) {
                    JOptionPane.showMessageDialog(this, "El entrenador con el nombre \"" + nombre + "\" ya existe.", "Dato duplicado", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (e.getCorreoElectronico().equals(correo)) {
                    JOptionPane.showMessageDialog(this, "El entrenador con el correo \"" + nombre + "\" ya existe.", "Dato duplicado", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (e.getTelefonoContacto().equals(telefono)) {
                    JOptionPane.showMessageDialog(this, "El entrenador con el Numero de telefono \"" + nombre + "\" ya existe.", "Dato duplicado", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (Arrays.equals(e.getHuellaDactilar(), datosHuella)) {
                JOptionPane.showMessageDialog(this, "Ya existe un entrenador registrado con esta misma huella digital.", "Huella duplicada", JOptionPane.ERROR_MESSAGE);
                return;
        }
            }

            // Crear nuevo entrenador
            Entrenador entrenador = new Entrenador();
            entrenador.setNombreCompleto(nombre);
            entrenador.setCorreoElectronico(correo);
            entrenador.setTelefonoContacto(telefono);
            entrenador.setHuellaDactilar(datosHuella); // Asegúrate que el atributo sea 'huella' o 'huellaDactilar' según tu entidad

            // Obtener el nombre de la especialidad seleccionada (String)
            String nombreEspecialidad = (String) comboEspecialidades.getSelectedItem();

            // Buscar el objeto Especialidades correspondiente
            Especialidades especialidad = null;
            for (Especialidades esp : especialidades) {
                if (esp.getNombreEspecialidad().equals(nombreEspecialidad)) {
                    especialidad = esp;
                    break;
                }
            }

            if (especialidad != null) {
                List<Especialidades> listaEsp = new ArrayList<>();
                listaEsp.add(especialidad);
                entrenador.setEspecialidadesList(listaEsp);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró la especialidad seleccionada.");
            }

            // Guardar en la base de datos
            cEntrenadores.create(entrenador); // Asegúrate de tener bien tu controlador JPA
            entrenadores.add(entrenador);
            mte.fireTableDataChanged();

            JOptionPane.showMessageDialog(this, "Entrenador registrado correctamente.");

            // Limpiar campos después del registro exitoso
            txtNombreEntrenador.setText("");
            txtCorreoEntrenador.setText("");
            txtTelefonoEntrenador.setText("");
            comboEspecialidades.setSelectedIndex(0);
            lector_huella.limpiarDatos();

        } catch (IllegalStateException ex) {
            JOptionPane.showMessageDialog(this, "Error al obtener huella: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    public boolean validarCampos(String campo2, String email, String telefono) {
    // Validación de campo2
    if (campo2.isEmpty()) {
        JOptionPane.showMessageDialog(null, "El campo de nombre no debe estar vacío.");
        return false;
    } else if (!campo2.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
        JOptionPane.showMessageDialog(null, "El nombre solo debe contener letras y espacios.");
        return false;
    }

    // Validación de email
    String emailRegex = "^[a-zA-Z0-9.]+@[a-zA-Z0-9-]+\\.[a-zA-Z]{2,6}$";
    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(null, "El correo electrónico no debe estar vacío.");
        return false;
    } else if (!email.matches(emailRegex)) {
        JOptionPane.showMessageDialog(null, "El correo electrónico no cumple con el formato estándar (ej: usuario@dominio.com).");
        return false;
    }

    // Validación de teléfono
    if (telefono.isEmpty()) {
        JOptionPane.showMessageDialog(null, "El número de teléfono no debe estar vacío.");
        return false;
    } else if (!telefono.matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "El teléfono solo debe contener números.");
        return false;
    } else if (telefono.length() != 10) {
        JOptionPane.showMessageDialog(null, "El número de teléfono debe contener exactamente 10 dígitos.");
        return false;
    }

    return true;
} 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lector_huella.iniciar();
        lector_huella.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        txtEditEntrenador.setEditable(true); // Activa el campo de nombre
        txtEditEntrenador.requestFocus();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        txtEditCorreo.setEditable(true); // Activa el campo de nombre
        txtEditCorreo.requestFocus();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        txtEditTelefono.setEditable(true); // Activa el campo de nombre
        txtEditTelefono.requestFocus();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        comboEditEspecialidad.setEditable(true); // Activa el campo de nombre
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnEditEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEntrenadorActionPerformed
        // TODO add your handling code here:
        String nombre = txtEditEntrenador.getText().trim();
        String correo = txtEditCorreo.getText().trim();
        String telefono = txtEditTelefono.getText().trim();

        boolean validar = validarCampos(nombre, correo, telefono);
        if (!validar) {
            return;
        }

        int filaSeleccionada = tableEntrenadores.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente para editar.", "Sin selección", JOptionPane.WARNING_MESSAGE);
            return;
        }
        byte[] datosHuella = null;

        try {
            // Intentar obtener una nueva huella
            datosHuella = lector_huella_new.obtenerDatosHuella();
        } catch (IllegalStateException ex) {
            // Si no se capturó ninguna huella, solo mostrar aviso informativo (no es un error)
            System.out.println("No se actualizó la huella: " + ex.getMessage());
            // También puedes mostrar un mensaje opcional al usuario:
            // JOptionPane.showMessageDialog(null, "No se actualizó la huella: " + ex.getMessage(), "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }

        try {

            // Crear nuevo entrenador
            Entrenador EntrenadorExiste = entrenadores.get(filaSeleccionada);

            EntrenadorExiste.setNombreCompleto(nombre);
            EntrenadorExiste.setCorreoElectronico(correo);
            EntrenadorExiste.setTelefonoContacto(telefono);
            // Actualizar huella solo si hay una nueva válida
            if (datosHuella != null && datosHuella.length > 0) {
                EntrenadorExiste.setHuellaDactilar(datosHuella);
            }

            // Obtener el nombre de la especialidad seleccionada (String)
            String nombreEspecialidad = (String) comboEditEspecialidad.getSelectedItem();

            // Buscar el objeto Especialidades correspondiente
            Especialidades especialidad = null;
            for (Especialidades esp : especialidades) {
                if (esp.getNombreEspecialidad().equals(nombreEspecialidad)) {
                    especialidad = esp;
                    break;
                }
            }

            if (especialidad != null) {
                List<Especialidades> listaEsp = new ArrayList<>();
                listaEsp.add(especialidad);
                EntrenadorExiste.setEspecialidadesList(listaEsp);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró la especialidad seleccionada.");
            }

            // Actualizar en base de datos
            cEntrenadores.edit(EntrenadorExiste);
            mte.fireTableRowsUpdated(filaSeleccionada, filaSeleccionada);
            lector_huella_new.limpiarDatos();

            JOptionPane.showMessageDialog(this, "Entrenador registrado correctamente.");

        } catch (IllegalStateException ex) {
            JOptionPane.showMessageDialog(this, "Error al obtener huella: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnEditEntrenadorActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Estás segur@ de regresar?\nSe perderán los datos no guardados.",
            "Confirmación",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            jTabbedPane1.setSelectedIndex(0);   // Ir al panel principal
            jTabbedPane1.setEnabledAt(2, false); // Desactivar pestaña de agregar
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        lector_huella_new.iniciar();
        lector_huella_new.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        lector_huella.limpiarDatos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Estás segur@ de regresar?\nSe perderán los datos no guardados.",
            "Confirmación",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            jTabbedPane1.setSelectedIndex(0);   // Ir al panel principal
            jTabbedPane1.setEnabledAt(2, false); // Desactivar pestaña de agregar
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void limpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiaActionPerformed
        // TODO add your handling code here:
        lector_huella_new.limpiarDatos();
    }//GEN-LAST:event_limpiaActionPerformed

    private void comboEditEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEditEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEditEspecialidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FechaA;
    private javax.swing.JLabel HoraA;
    private javax.swing.JTextArea area_huella;
    private javax.swing.JTextArea area_huella2;
    private javax.swing.JButton btnAgregarEntrenador;
    private javax.swing.JButton btnEditEntrenador;
    private javax.swing.JButton btnEditarEntrenador;
    private javax.swing.JButton btnEliminarEntrenador;
    private javax.swing.JComboBox<String> comboEditEspecialidad;
    private javax.swing.JComboBox<String> comboEspecialidades;
    private javax.swing.JLabel imagen_huella;
    private javax.swing.JLabel imagen_huella2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton limpia;
    private javax.swing.JTable tableEntrenadores;
    private javax.swing.JTextField txtCorreoEntrenador;
    private javax.swing.JTextField txtEditCorreo;
    private javax.swing.JTextField txtEditEntrenador;
    private javax.swing.JTextField txtEditTelefono;
    private javax.swing.JTextField txtNombreEntrenador;
    private javax.swing.JTextField txtTelefonoEntrenador;
    // End of variables declaration//GEN-END:variables
}
