/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;


import control.AdmDatos;
import control.ClientesJpaController;
import control.MembresiaJpaController;
import control.PagomembresiaJpaController;
import control.exceptions.IllegalOrphanException;
import control.exceptions.NonexistentEntityException;
import control_datos.MtCliente;
import control_datos.MtMembresia;
import control_datos.MtPagomembresia;
import huella.huella;
import java.awt.HeadlessException;
import java.awt.Rectangle;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import modelo.Clientes;
import modelo.Entrenador;
import modelo.Membresia;
import modelo.Pagomembresia;

/**
 *
 * @author abiga
 */
public class PanelClientes extends javax.swing.JPanel {
private boolean esDueno;
private huella lector_huella ;
private huella lector_huella_new ;//Para actualizar la huella


//Datos persistentes tabla Clientes
private Clientes cliente;
private final ClientesJpaController cClientes;
//Datos persistentes tabla Membresias
private Membresia Membresia;
private final MembresiaJpaController cMembresias;
//Datos persistentes tabla Pagomembresia
private Pagomembresia pagomembresia;
private final PagomembresiaJpaController cPagomembresias;

private final AdmDatos adm;

private final List<Clientes> clientes;
private final List<Membresia> membresias;
private final List<Pagomembresia> pagomembresias;

private final MtCliente mtc;
private final MtMembresia mtm;
private final MtPagomembresia mtp;
private Clientes clienteSeleccionado;
    /**
     * Creates new form PanelClientes
     */
    public PanelClientes() {
        initComponents();

    adm = new AdmDatos();
    
    //Inicializacion de datos clientes
    cClientes = new ClientesJpaController(adm.getEmf());
    clientes = cClientes.findClientesEntities();
    mtc = new MtCliente(clientes);
    tableCliente.setModel(mtc);
    
    //Inicializacion de datos membresias
    cMembresias = new MembresiaJpaController(adm.getEmf());
    membresias = cMembresias.findMembresiaEntities();
    mtm = new MtMembresia(membresias);
    
    //Inicializacion de datos Pagomembresia
    cPagomembresias = new PagomembresiaJpaController(adm.getEmf());
    pagomembresias = cPagomembresias.findPagomembresiaEntities();
    mtp = new MtPagomembresia(pagomembresias);


    lector_huella = new huella(imagen_huella, area_huella);
    lector_huella_new = new huella(imagen_huella_new, area_huella_new);

    // Bloquear los datos del cliente cuando entre a la vista donde los edita
    txtEditNombre.setEditable(false); // nombre
    txtEditEmail.setEditable(false); // correo
    txtEditTelefono.setEditable(false); // teléfono

    // Desactivar pestañas (excepto la 0: Vista de Clientes)
    jTabbedPane1.setEnabledAt(1, false); // Agregar Clientes
    jTabbedPane1.setEnabledAt(2, false); // Editar Clientes
    jTabbedPane1.setEnabledAt(3, false); // Control Membresía

    // Mostrar la fecha
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    String fechaActual = formato.format(new Date());
    FechaA.setText(fechaActual); // Fecha en el registro de clientes
    FechaM.setText(fechaActual); // Fecha en el registro de membresías

    // Inicia la hora actual con formato
    SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
    // Crear un Timer que se ejecuta cada 1000 ms (1 segundo)
    Timer timer = new Timer(1000, e -> {
        String horaActual = formatoHora.format(new Date());
        HoraA.setText(horaActual);
    });
    timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnMembresias = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCliente = new javax.swing.JTable();
        btnAgregarMembresia = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        imagen_huella = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        FechaA = new javax.swing.JLabel();
        HoraA = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area_huella = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnNuevaHuella = new javax.swing.JButton();
        txtEditNombre = new javax.swing.JTextField();
        txtEditEmail = new javax.swing.JTextField();
        txtEditTelefono = new javax.swing.JTextField();
        imagen_huella_new = new javax.swing.JLabel();
        btnEditNombre = new javax.swing.JButton();
        btnEditEmail = new javax.swing.JButton();
        btnEditTelefono = new javax.swing.JButton();
        btnEditCLIENTE = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        area_huella_new = new javax.swing.JTextArea();
        btnNuevaHuella1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelNombreCliente = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        comboTipoMembresia = new javax.swing.JComboBox<>();
        labelFechaInicio = new javax.swing.JLabel();
        labelFechaFin = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        comboMetodoPago = new javax.swing.JComboBox<>();
        FechaM = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        labelNombreCliente1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        labelid = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        comboMembresia = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        comboMetodoPago1 = new javax.swing.JComboBox<>();
        jButton15 = new javax.swing.JButton();
        chooserInicio = new com.toedter.calendar.JDateChooser();
        chooserFin = new com.toedter.calendar.JDateChooser();
        txtPrecio = new javax.swing.JTextField();
        btnGuardarMembresia = new javax.swing.JButton();

        setBackground(new java.awt.Color(26, 26, 26));

        jTabbedPane1.setBackground(new java.awt.Color(38, 38, 38));
        jTabbedPane1.setForeground(new java.awt.Color(38, 38, 38));

        jPanel1.setBackground(new java.awt.Color(38, 38, 38));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administación De Clientes");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEditarCliente.setBackground(new java.awt.Color(51, 51, 51));
        btnEditarCliente.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEditarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCliente.setText("Editar");
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminarCliente.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEliminarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        btnMembresias.setBackground(new java.awt.Color(51, 51, 51));
        btnMembresias.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnMembresias.setForeground(new java.awt.Color(255, 255, 255));
        btnMembresias.setText("Membresias");
        btnMembresias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMembresiasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        btnBuscarCliente.setBackground(new java.awt.Color(51, 51, 51));
        btnBuscarCliente.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        tableCliente.setBackground(new java.awt.Color(34, 34, 34));
        tableCliente.setForeground(new java.awt.Color(255, 255, 255));
        tableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableCliente);

        btnAgregarMembresia.setText("Agregar Membresia");
        btnAgregarMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMembresiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnMembresias, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnBuscarCliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(btnAgregarMembresia)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarCliente)
                    .addComponent(btnEditarCliente)
                    .addComponent(jButton1)
                    .addComponent(btnMembresias))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarMembresia)
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("VISTA DE CLIENTES ", jPanel1);

        jPanel2.setBackground(new java.awt.Color(38, 38, 38));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agregar Clientes ");

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Resgistra Cliente ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correo");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono");

        imagen_huella.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        imagen_huella.setForeground(new java.awt.Color(255, 255, 255));
        imagen_huella.setText("Aqui para la Huuella ");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        numero.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });
        numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroKeyTyped(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Capturar Huella");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        FechaA.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        FechaA.setForeground(new java.awt.Color(255, 255, 255));
        FechaA.setText("12/12/2024");

        HoraA.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        HoraA.setForeground(new java.awt.Color(255, 255, 255));
        HoraA.setText("9:00");

        area_huella.setColumns(20);
        area_huella.setRows(5);
        jScrollPane2.setViewportView(area_huella);

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Limpiar Huella");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Regresar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HoraA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FechaA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(numero))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(imagen_huella, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton8)
                        .addGap(184, 184, 184))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jButton5)
                .addGap(77, 77, 77)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FechaA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(HoraA)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imagen_huella, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addGap(47, 47, 47))))
        );

        jTabbedPane1.addTab("AGREGAR CLIENTES", jPanel2);

        jPanel3.setBackground(new java.awt.Color(38, 38, 38));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Editar Datos De Un Cliente ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correo ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Telefono");

        btnNuevaHuella.setBackground(new java.awt.Color(51, 51, 51));
        btnNuevaHuella.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnNuevaHuella.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaHuella.setText("Nueva Huella");
        btnNuevaHuella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaHuellaActionPerformed(evt);
            }
        });

        txtEditNombre.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtEditNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditNombreActionPerformed(evt);
            }
        });

        txtEditEmail.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        txtEditTelefono.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        imagen_huella_new.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        imagen_huella_new.setForeground(new java.awt.Color(255, 255, 255));
        imagen_huella_new.setText("Nueva HUella ");

        btnEditNombre.setBackground(new java.awt.Color(51, 51, 51));
        btnEditNombre.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEditNombre.setForeground(new java.awt.Color(255, 255, 255));
        btnEditNombre.setText("Editar");
        btnEditNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditNombreActionPerformed(evt);
            }
        });

        btnEditEmail.setBackground(new java.awt.Color(51, 51, 51));
        btnEditEmail.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEditEmail.setForeground(new java.awt.Color(255, 255, 255));
        btnEditEmail.setText("Editar");
        btnEditEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditEmailActionPerformed(evt);
            }
        });

        btnEditTelefono.setBackground(new java.awt.Color(51, 51, 51));
        btnEditTelefono.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEditTelefono.setForeground(new java.awt.Color(255, 255, 255));
        btnEditTelefono.setText("Editar");
        btnEditTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTelefonoActionPerformed(evt);
            }
        });

        btnEditCLIENTE.setBackground(new java.awt.Color(51, 51, 51));
        btnEditCLIENTE.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEditCLIENTE.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCLIENTE.setText("Guardar Cambios");
        btnEditCLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCLIENTEActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(51, 51, 51));
        jButton17.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("Regresar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        area_huella_new.setColumns(20);
        area_huella_new.setRows(5);
        jScrollPane3.setViewportView(area_huella_new);

        btnNuevaHuella1.setBackground(new java.awt.Color(51, 51, 51));
        btnNuevaHuella1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnNuevaHuella1.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaHuella1.setText("Limpiar Huella");
        btnNuevaHuella1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaHuella1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEditTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtEditNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(txtEditEmail))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEditNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEditEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEditTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(btnNuevaHuella)
                        .addGap(43, 43, 43)
                        .addComponent(btnNuevaHuella1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(imagen_huella_new, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btnEditCLIENTE)
                        .addGap(113, 113, 113)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEditNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtEditTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditTelefono))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnNuevaHuella))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevaHuella1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagen_huella_new, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditCLIENTE)
                    .addComponent(jButton17))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("EDITAR CLIENTE", jPanel3);

        jPanel4.setBackground(new java.awt.Color(38, 38, 38));
        jPanel4.setForeground(new java.awt.Color(38, 38, 38));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Control De Membresia");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cliente:");

        labelNombreCliente.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelNombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreCliente.setText("jLabel15");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ID:");

        labelID.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelID.setForeground(new java.awt.Color(255, 255, 255));
        labelID.setText("jLabel17");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Estado: ");

        labelEstado.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelEstado.setForeground(new java.awt.Color(255, 255, 255));
        labelEstado.setText("jLabel19");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Fecha Inicio:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Tipo de mebresia:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Fecha Vencimiento:");

        comboTipoMembresia.setBackground(new java.awt.Color(51, 51, 51));
        comboTipoMembresia.setForeground(new java.awt.Color(255, 255, 255));
        comboTipoMembresia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensual", "Anual" }));
        comboTipoMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoMembresiaActionPerformed(evt);
            }
        });

        labelFechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        labelFechaInicio.setText("jLabel23");

        labelFechaFin.setForeground(new java.awt.Color(255, 255, 255));
        labelFechaFin.setText("jLabel24");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Metodo de pago :");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Total a pagar:");

        labelPrecio.setForeground(new java.awt.Color(255, 255, 255));
        labelPrecio.setText("jLabel27");

        comboMetodoPago.setBackground(new java.awt.Color(51, 51, 51));
        comboMetodoPago.setForeground(new java.awt.Color(255, 255, 255));
        comboMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta", "Efectivo" }));

        FechaM.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        FechaM.setForeground(new java.awt.Color(255, 255, 255));
        FechaM.setText("12/12/2004");

        jButton14.setBackground(new java.awt.Color(51, 51, 51));
        jButton14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Regresar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FechaM))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(168, 168, 168))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel25)
                                                .addGap(18, 18, 18)
                                                .addComponent(comboMetodoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addGap(18, 18, 18)
                                                .addComponent(comboTipoMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(labelNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(97, 97, 97)
                                    .addComponent(jLabel16)
                                    .addGap(18, 18, 18)
                                    .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(140, 140, 140)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(labelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(56, 56, 56))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(FechaM))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(labelNombreCliente)
                    .addComponent(jLabel16)
                    .addComponent(labelID))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(labelEstado))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(comboTipoMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(labelFechaInicio))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(labelFechaFin))
                .addGap(58, 58, 58)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(labelPrecio))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(comboMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton14)
                .addGap(70, 70, 70))
        );

        jTabbedPane1.addTab("CONTROLAR MEBRESIA", jPanel4);

        jPanel5.setBackground(new java.awt.Color(38, 38, 38));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Control De Membresia");

        labelNombreCliente1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelNombreCliente1.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreCliente1.setText("jLabel15");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Cliente:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ID:");

        labelid.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelid.setForeground(new java.awt.Color(255, 255, 255));
        labelid.setText("jLabel17");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Tipo de mebresia:");

        comboMembresia.setBackground(new java.awt.Color(51, 51, 51));
        comboMembresia.setForeground(new java.awt.Color(255, 255, 255));
        comboMembresia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensual", "Anual", "Prueba", " " }));
        comboMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMembresiaActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Fecha Inicio:");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Fecha Vencimiento:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Total a pagar:");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Metodo de pago :");

        comboMetodoPago1.setBackground(new java.awt.Color(51, 51, 51));
        comboMetodoPago1.setForeground(new java.awt.Color(255, 255, 255));
        comboMetodoPago1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta", "Efectivo" }));

        jButton15.setBackground(new java.awt.Color(51, 51, 51));
        jButton15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Regresar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        btnGuardarMembresia.setBackground(new java.awt.Color(51, 51, 51));
        btnGuardarMembresia.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnGuardarMembresia.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarMembresia.setText("Guardar");
        btnGuardarMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMembresiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboMetodoPago1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chooserFin, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(labelNombreCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(97, 97, 97)
                                    .addComponent(jLabel19))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(comboMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chooserInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 54, Short.MAX_VALUE)
                        .addComponent(labelid, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel15)
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(labelNombreCliente1)
                    .addComponent(jLabel19)
                    .addComponent(labelid))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(comboMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(chooserInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(chooserFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(comboMetodoPago1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(btnGuardarMembresia))
                .addGap(70, 70, 70))
        );

        jTabbedPane1.addTab("Registrar Membresia", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed

        // Obtener el índice de la fila seleccionada en la tabla
        int filaSeleccionada = tableCliente.getSelectedRow();

        // Verificar si hay alguna fila seleccionada
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor, seleccione un cliente para editar.",
                "Ninguna selección",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        jTabbedPane1.setEnabledAt(2, true);
        jTabbedPane1.setSelectedIndex(2);

        // Obtener valores de la fila seleccionada y colocarlos en los txtFields
        txtEditNombre.setText(tableCliente.getValueAt(filaSeleccionada, 1).toString());
        txtEditEmail.setText(tableCliente.getValueAt(filaSeleccionada, 2).toString());
        txtEditTelefono.setText(tableCliente.getValueAt(filaSeleccionada, 3).toString());

    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed

        // Obtener el índice de la fila seleccionada en la tabla
        int filaSeleccionada = tableCliente.getSelectedRow();

        // Verificar si hay alguna fila seleccionada
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor, seleccione un cliente para eliminar.",
                "Ninguna selección",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Confirmar eliminación con el usuario
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Está seguro de que desea eliminar éste cliente?",
            "Confirmar eliminación",
            javax.swing.JOptionPane.YES_NO_OPTION);

        // Si el usuario confirma la eliminación
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            try {
                // Obtener el cliente seleccionado
                Clientes clienteSeleccionado = clientes.get(filaSeleccionada);

                // Obtener el ID del cliente (idcliente es un Integer según la clase TutorJpaController)
                Integer idCliente = clienteSeleccionado.getClienteId();

                // Eliminar de la base de datos usando el ID
                cClientes.destroy(idCliente);

                // Eliminar de la lista local
                clientes.remove(filaSeleccionada);

                // Actualizar la tabla
                mtc.fireTableDataChanged();

                // Mostrar mensaje de éxito
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Cliente eliminado correctamente.",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            } catch (NonexistentEntityException e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Error: El Cliente ya no existe en la base de datos.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                // Actualizar la tabla de todas formas
                clientes.remove(filaSeleccionada);
                mtc.fireTableDataChanged();
            } catch (HeadlessException e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al eliminar el cliente: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            } catch (IllegalOrphanException ex) {
                Logger.getLogger(PanelClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnMembresiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMembresiasActionPerformed
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");

        int filaSeleccionada = tableCliente.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un cliente.");
            return;
        }

        // Obtener cliente desde el modelo
        Clientes clienteSeleccionado = mtc.getClienteAt(filaSeleccionada);

        // Buscar la membresía correspondiente al cliente
        Membresia membresiaSeleccionada = null;
        for (Membresia m : membresias) {
            if (m.getClienteId().getClienteId().equals(clienteSeleccionado.getClienteId())) {
                membresiaSeleccionada = m;
                break;
            }
        }

        if (membresiaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "No se encontró una membresía para este cliente.");
            return;
        }

        // Buscar el pago correspondiente a la membresía
        Pagomembresia pagoSeleccionado = null;
        for (Pagomembresia p : pagomembresias) {
            if (p.getMembresiaId().getMembresiaId().equals(membresiaSeleccionada.getMembresiaId())) {
                pagoSeleccionado = p;
                break;
            }
        }

        if (pagoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "No se encontró un pago para esta membresía.");
            return;
        }

        // Asignar los valores a los labels y combos
        labelNombreCliente.setText(clienteSeleccionado.getNombreCompleto());
        labelID.setText(Integer.toString(clienteSeleccionado.getClienteId()));
        labelEstado.setText(membresiaSeleccionada.getEstadoMembresia());
        comboTipoMembresia.setSelectedItem(membresiaSeleccionada.getTipoMembresia());
        labelFechaInicio.setText(formatoFecha.format(membresiaSeleccionada.getFechaInicio()));
        labelFechaFin.setText(formatoFecha.format(membresiaSeleccionada.getFechaVencimiento()));
        labelPrecio.setText(String.valueOf(membresiaSeleccionada.getPrecio()));
        comboMetodoPago.setSelectedItem(pagoSeleccionado.getMetodoPago());

        jTabbedPane1.setEnabledAt(3, true);
        jTabbedPane1.setSelectedIndex(3);

    }//GEN-LAST:event_btnMembresiasActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombreCliente.getText().trim();
        if (!nombre.isEmpty()) {
            buscarYSeleccionarNombreEnTabla(nombre);
        } else {
            JOptionPane.showMessageDialog(this, "Ingresa un nombre para buscar.");
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void buscarYSeleccionarNombreEnTabla(String nombreBuscado) {
    MtCliente modelo = (MtCliente) tableCliente.getModel();

    for (int fila = 0; fila < modelo.getRowCount(); fila++) {
        Clientes cliente = modelo.getClienteAt(fila);
        if (cliente != null && cliente.getNombreCompleto().equalsIgnoreCase(nombreBuscado)) {
            tableCliente.setRowSelectionInterval(fila, fila);
            tableCliente.scrollRectToVisible(new Rectangle(tableCliente.getCellRect(fila, 0, true)));
            JOptionPane.showMessageDialog(this, "Cliente encontrado.");
            txtNombreCliente.setText("");  // <-- Limpiar el campo de texto
            return;
        }
    }

    JOptionPane.showMessageDialog(this, "Cliente no encontrado.");
}
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        String campo2 = jTextField2.getText().trim();
        String email = jTextField3.getText().trim();
        String telefono = numero.getText().trim();

        boolean validar = validarCampos(campo2, email, telefono);
        if (!validar) {
            return;
        }

        Date fechaActual = new Date();
        try {
            byte[] datos_huella = lector_huella.obtenerDatosHuella(); 
            if (datos_huella == null || datos_huella.length == 0) {
                JOptionPane.showMessageDialog(null, "No se pudo obtener la huella digital.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Detener ejecución si datos_huella está vacío
            }

            // 2. Verificar si el tutor ya existe (por número de tarjeta, por ejemplo)
            for (Clientes c : clientes) {
                if (c.getNombreCompleto().equalsIgnoreCase(campo2)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "El cliente con el nombre " + campo2 + " ya existe.", "Dato Duplicado", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return; // Detener la ejecución si el tutor ya existe
                }
                if (c.getCorreoElectronico().equals(email)) {
                    JOptionPane.showMessageDialog(this, "El cliente con el correo \"" + email + "\" ya existe.", "Dato duplicado", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (c.getTelefonoContacto().equals(telefono)) {
                    JOptionPane.showMessageDialog(this, "El cliente con el Numero de telefono \"" + telefono + "\" ya existe.", "Dato duplicado", JOptionPane.ERROR_MESSAGE);
                    return;
                }

            }

            cliente=new Clientes();
            cliente.setNombreCompleto(campo2);
            cliente.setCorreoElectronico(email);
            cliente.setTelefonoContacto(telefono);
            cliente.setFechaRegistro(fechaActual);
            cliente.setHuellaDactilar(datos_huella);

            cClientes.create(cliente);
            clientes.add(cliente);
            mtc.fireTableDataChanged();

            JOptionPane.showMessageDialog(null, "Cliente registrado correctamente.");
            // Limpiar campos después del registro exitoso
            jTextField2.setText("");
            jTextField3.setText("");
            numero.setText("");
            lector_huella.limpiarDatos();

        } catch (IllegalStateException ex) {
            JOptionPane.showMessageDialog(null, "Error al obtener huella: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    public boolean validarCampos(String campo2, String email, String telefono) {
    // Validación de campo2
    if (campo2.isEmpty()) {
        JOptionPane.showMessageDialog(null, "El campo de nombre no debe estar vacío.");
        return false;
    } else if (!campo2.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
        JOptionPane.showMessageDialog(null, "El nombre solo debe contener letras y espacios.");
        return false;
    }

    // Validación de email
    String emailRegex = "^[a-zA-Z0-9.]+@[a-zA-Z0-9-]+\\.[a-zA-Z]{2,6}$";
    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(null, "El correo electrónico no debe estar vacío.");
        return false;
    } else if (!email.matches(emailRegex)) {
        JOptionPane.showMessageDialog(null, "El correo electrónico no cumple con el formato estándar (ej: usuario@dominio.com).");
        return false;
    }

    // Validación de teléfono
    if (telefono.isEmpty()) {
        JOptionPane.showMessageDialog(null, "El número de teléfono no debe estar vacío.");
        return false;
    } else if (!telefono.matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "El teléfono solo debe contener números.");
        return false;
    } else if (telefono.length() != 10) {
        JOptionPane.showMessageDialog(null, "El número de teléfono debe contener exactamente 10 dígitos.");
        return false;
    }

    return true;
} 
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped

    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped

    }//GEN-LAST:event_jTextField3KeyTyped

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void numeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroKeyTyped

    }//GEN-LAST:event_numeroKeyTyped

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        lector_huella.iniciar();
        lector_huella.start();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnNuevaHuellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaHuellaActionPerformed
        // TODO add your handling code here:
        lector_huella_new.iniciar();
        lector_huella_new.start();
    }//GEN-LAST:event_btnNuevaHuellaActionPerformed

    private void txtEditNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditNombreActionPerformed

    private void btnEditNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditNombreActionPerformed
        txtEditNombre.setEditable(true); // Activa el campo de nombre
        txtEditNombre.requestFocus();    // Pone el cursor ahí
    }//GEN-LAST:event_btnEditNombreActionPerformed

    private void btnEditEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEmailActionPerformed
        txtEditEmail.setEditable(true);
        txtEditEmail.requestFocus();
    }//GEN-LAST:event_btnEditEmailActionPerformed

    private void btnEditTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTelefonoActionPerformed
        txtEditTelefono.setEditable(true);
        txtEditTelefono.requestFocus();
    }//GEN-LAST:event_btnEditTelefonoActionPerformed

    private void btnEditCLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCLIENTEActionPerformed
        // TODO add your handling code here:
        String campo2 = txtEditNombre.getText().trim();
        String email = txtEditEmail.getText().trim();
        String telefono = txtEditTelefono.getText().trim();

        boolean validar = validarCampos(campo2, email, telefono);
        if (!validar) {
            return;
        }

        int filaSeleccionada = tableCliente.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente para editar.", "Sin selección", JOptionPane.WARNING_MESSAGE);
            return;
        }

        byte[] datos_huella = null;

        try {
            // Intentar obtener una nueva huella
            datos_huella = lector_huella_new.obtenerDatosHuella();
        } catch (IllegalStateException ex) {
            // Si no se capturó ninguna huella, solo mostrar aviso informativo (no es un error)
            System.out.println("No se actualizó la huella: " + ex.getMessage());
            // También puedes mostrar un mensaje opcional al usuario:
            // JOptionPane.showMessageDialog(null, "No se actualizó la huella: " + ex.getMessage(), "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }

        try {
            Clientes clienteExistente = clientes.get(filaSeleccionada);

            // Actualizar datos básicos
            clienteExistente.setNombreCompleto(campo2);
            clienteExistente.setCorreoElectronico(email);
            clienteExistente.setTelefonoContacto(telefono);

            // Actualizar huella solo si hay una nueva válida
            if (datos_huella != null && datos_huella.length > 0) {
                clienteExistente.setHuellaDactilar(datos_huella);
            }

            // Actualizar en base de datos
            cClientes.edit(clienteExistente);
            mtc.fireTableRowsUpdated(filaSeleccionada, filaSeleccionada);
            lector_huella_new.limpiarDatos();

            JOptionPane.showMessageDialog(null, "Cliente actualizado correctamente.");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al actualizar cliente: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEditCLIENTEActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Estás segur@ de que deseas salir sin guardar cambios?",
            "Confirmación",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            jTabbedPane1.setSelectedIndex(0);
            jTabbedPane1.setEnabledAt(2, false);
        }

        // Limpiar campos después del registro exitoso
        txtEditNombre.setText("");
        txtEditEmail.setText("");
        txtEditTelefono.setText("");
        lector_huella.limpiarDatos();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void comboTipoMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoMembresiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoMembresiaActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Estás segur@ de que deseas salir sin guardar cambios?",
            "Confirmación",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            jTabbedPane1.setSelectedIndex(0);
            jTabbedPane1.setEnabledAt(3, false);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        lector_huella.limpiarDatos();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnNuevaHuella1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaHuella1ActionPerformed
        // TODO add your handling code here:
        lector_huella_new.limpiarDatos();
    }//GEN-LAST:event_btnNuevaHuella1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Estás segur@ de que deseas salir sin guardar cambios?",
            "Confirmación",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            jTabbedPane1.setSelectedIndex(0);
            jTabbedPane1.setEnabledAt(3, false);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void comboMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMembresiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMembresiaActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Estás segur@ de que deseas salir sin guardar cambios?",
            "Confirmación",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            jTabbedPane1.setSelectedIndex(0);
            jTabbedPane1.setEnabledAt(3, false);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void btnAgregarMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMembresiaActionPerformed


        int filaSeleccionada = tableCliente.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un cliente.");
            return;
        }

        // Obtener cliente desde el modelo
        clienteSeleccionado = mtc.getClienteAt(filaSeleccionada);
        // Asignar los valores a los labels y combos
        labelNombreCliente1.setText(clienteSeleccionado.getNombreCompleto());
        labelid.setText(Integer.toString(clienteSeleccionado.getClienteId()));
        
        jTabbedPane1.setEnabledAt(4, true);
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btnAgregarMembresiaActionPerformed

    private void btnGuardarMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMembresiaActionPerformed

    try {
        if (clienteSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Primero selecciona un cliente.");
            return;
        }

        String tipo = comboMembresia.getSelectedItem().toString();
        String estado = "Activo".toLowerCase().trim();

        String precioTexto = txtPrecio.getText().trim();
        if (precioTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa el precio de la membresía.");
            return;
        }

        BigDecimal precioDecimal;
        try {
            precioDecimal = new BigDecimal(precioTexto);
            if (precioDecimal.compareTo(BigDecimal.ZERO) <= 0) {
                JOptionPane.showMessageDialog(this, "El precio debe ser mayor a cero.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio ingresado no es válido.");
            return;
        }

        Date fechaInicioDate = chooserInicio.getDate();
        Date fechaVencimientoDate = chooserFin.getDate();

        if (fechaInicioDate == null || fechaVencimientoDate == null) {
            JOptionPane.showMessageDialog(this, "Selecciona ambas fechas.");
            return;
        }

        if (fechaInicioDate.after(fechaVencimientoDate)) {
            JOptionPane.showMessageDialog(this, "La fecha de inicio no puede ser posterior a la fecha de vencimiento.");
            return;
        }

        String metodo = comboMetodoPago1.getSelectedItem().toString();
        if (metodo == null || metodo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona un método de pago válido.");
            return;
        }

        Membresia membresia = new Membresia();
        membresia.setClienteId(clienteSeleccionado);
        membresia.setTipoMembresia(tipo);
        membresia.setFechaInicio(fechaInicioDate);
        membresia.setFechaVencimiento(fechaVencimientoDate);
        membresia.setEstadoMembresia(estado);
        membresia.setPrecio(precioDecimal);

        cMembresias.create(membresia);
        membresias.add(membresia);
        mtm.fireTableDataChanged();

        Pagomembresia pago = new Pagomembresia();
        pago.setClienteId(clienteSeleccionado);
        pago.setMembresiaId(membresia);
        pago.setFechaPago(fechaInicioDate);
        pago.setMontoPago(precioDecimal);
        pago.setMetodoPago(metodo);

        cPagomembresias.create(pago);
        pagomembresias.add(pago);
        mtp.fireTableDataChanged();

        JOptionPane.showMessageDialog(this, "Membresía y pago registrados correctamente.");

        // Limpieza
        comboMembresia.setSelectedIndex(0);
        txtPrecio.setText("");
        chooserInicio.setDate(null);
        chooserFin.setDate(null);
        comboMetodoPago1.setSelectedIndex(0);

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al guardar la membresía: " + ex.getMessage());
        ex.printStackTrace();
    }

    }//GEN-LAST:event_btnGuardarMembresiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FechaA;
    private javax.swing.JLabel FechaM;
    private javax.swing.JLabel HoraA;
    private javax.swing.JTextArea area_huella;
    private javax.swing.JTextArea area_huella_new;
    private javax.swing.JButton btnAgregarMembresia;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnEditCLIENTE;
    private javax.swing.JButton btnEditEmail;
    private javax.swing.JButton btnEditNombre;
    private javax.swing.JButton btnEditTelefono;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnGuardarMembresia;
    private javax.swing.JButton btnMembresias;
    private javax.swing.JButton btnNuevaHuella;
    private javax.swing.JButton btnNuevaHuella1;
    private com.toedter.calendar.JDateChooser chooserFin;
    private com.toedter.calendar.JDateChooser chooserInicio;
    private javax.swing.JComboBox<String> comboMembresia;
    private javax.swing.JComboBox<String> comboMetodoPago;
    private javax.swing.JComboBox<String> comboMetodoPago1;
    private javax.swing.JComboBox<String> comboTipoMembresia;
    private javax.swing.JLabel imagen_huella;
    private javax.swing.JLabel imagen_huella_new;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelFechaFin;
    private javax.swing.JLabel labelFechaInicio;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNombreCliente;
    private javax.swing.JLabel labelNombreCliente1;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelid;
    private javax.swing.JTextField numero;
    private javax.swing.JTable tableCliente;
    private javax.swing.JTextField txtEditEmail;
    private javax.swing.JTextField txtEditNombre;
    private javax.swing.JTextField txtEditTelefono;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
